package event;

/**
 * Перечисление возможных вариантов события
 */
public enum Event {
    GET_DRUGS_WITH_PARAMETERS,GET_DRUGSTORE_WITH_PARAMETERS, ADD_DRUG, ADD_DRUGSTORE, UPDATE_DRUG, UPDATE_DRUGSTORE,
    DELETE_DRUG, DELETE_DRUGSTORE, GET_ALL_DRUGS, GET_ALL_DRUGSTORES, ADD_P_EFFECT, ADD_T_EFFECT, GET_ALL_P_EFFECTS,
    GET_ALL_T_EFFECTS, ADD_PRICE, UPDATE_PRICE, DELETE_PRICE, GET_ALL_PRICES, EXPORT, IMPORT
}
