package event;

/**
 * Перечисление возможных вариантов события
 */
public enum Event {
    GET_DRUGS_WITH_PARAMETERS,GET_DRUGSTORE_WITH_PARAMETERS, ADD_DRUG, ADD_DRUGSTORE, UPDATE_DRUG, UPDATE_DRUGSTORE,
    DELETE_DRUG, DELTE_DRUGSTORE, GET_ALL_DRUGS, GET_ALL_DRUGSTORE
}
